require-stack-version: ">= 1.5"

resolver: lts-9.0

packages:
- .
- jni
- jvm
- jvm-streaming
- examples/classpath

nix:
  shell-file: shell.nix

docker:
  enable: false
  image: tweag/inline-java
  stack-exe: image
