version: 2
jobs:
  build:
    working_directory: ~/inline-java
    docker:
    - image: tweag/inline-java
    steps:
    - checkout
    - restore_cache:
        key: inline-java-stack-dependencies
    - run:
        name: build dependencies
        command: |
          # XXX Workaround https://github.com/commercialhaskell/stack/issues/595
          stack --no-terminal build alex happy
          stack --no-terminal build --only-dependencies --prefetch --test --bench
    - save_cache:
        key: inline-java-stack-dependencies
        paths:
        - ~/.stack
    - run:
        name: build project
        command: stack --no-terminal build --pedantic --test --bench --no-run-tests --no-run-benchmarks
    - run:
        name: test
        command: stack --no-terminal test
